#!/usr/bin/env bash
set -euo pipefail

APP_NAME="flow"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_BIN="$SCRIPT_DIR/$APP_NAME"
INSTALL_DIR="${FLOW_INSTALL_DIR:-/usr/local/bin}"
HOOK_DIR="$HOME/.flow/hooks"

timestamp() {
    date +%Y%m%d_%H%M%S
}

backup_file() {
    local file="$1"
    [ -f "$file" ] && cp "$file" "$file.flow_backup.$(timestamp)"
}

install_binary() {
    if [ ! -f "$SRC_BIN" ]; then
        echo "❌ Cannot find compiled '$APP_NAME' binary next to this installer."
        echo "Expected: $SRC_BIN"
        echo "Build first, then put install.sh beside the flow binary."
        exit 1
    fi

    echo "📦 Installing $APP_NAME to $INSTALL_DIR..."
    if [ -w "$INSTALL_DIR" ]; then
        install -m 755 "$SRC_BIN" "$INSTALL_DIR/$APP_NAME"
    else
        sudo mkdir -p "$INSTALL_DIR"
        sudo install -m 755 "$SRC_BIN" "$INSTALL_DIR/$APP_NAME"
    fi
}

write_bash_hook() {
    mkdir -p "$HOOK_DIR"

    cat > "$HOOK_DIR/flow.bash" <<'BASH_HOOK'
# --- Flow Automation Hook: bash ---
# Captures interactive bash commands before execution.
# Bash has no native preexec hook, so Flow uses DEBUG trap.

case $- in
    *i*) ;;
    *) return 0 2>/dev/null || exit 0 ;;
esac

unset -f __flow_bash_capture 2>/dev/null || true

if [ -n "${PROMPT_COMMAND:-}" ]; then
    PROMPT_COMMAND="$(printf '%s\n' "$PROMPT_COMMAND" \
        | sed 's/__flow_bash_capture;*//g; s/;;*/;/g; s/^;//; s/;$//')"
    [ -z "$PROMPT_COMMAND" ] && unset PROMPT_COMMAND
fi

__flow_bash_debug_trap() {
    [[ -n "${__FLOW_INTERNAL_TRAP:-}" ]] && return
    __FLOW_INTERNAL_TRAP=1

    # Only record while Flow is active. This prevents startup junk from being cached.
    if [ "$(cat /tmp/.flow_active_state 2>/dev/null)" != "1" ]; then
        unset __FLOW_INTERNAL_TRAP
        return
    fi

    local cmd="$BASH_COMMAND"

    # Normalize common aliases/defaults.
    cmd="${cmd/ls --color=auto/ls}"

    case "$cmd" in
        "" ) ;;
        flow|flow\ *|command\ flow|command\ flow\ * ) ;;
        __flow_* ) ;;
        trap\ * ) ;;
        PROMPT_COMMAND=* ) ;;
        unset\ PROMPT_COMMAND* ) ;;
        unset\ -f\ __flow_* ) ;;
        source\ *flow.bash* ) ;;
        .\ *flow.bash* ) ;;
        cmd=\"\$BASH_COMMAND\" ) ;;
        cmd=\$BASH_COMMAND ) ;;
        local\ cmd ) ;;
        __FLOW_INTERNAL_TRAP=* ) ;;
        * )
            command flow _hook "$cmd" >/dev/null 2>&1
            ;;
    esac

    unset __FLOW_INTERNAL_TRAP
}

trap '__flow_bash_debug_trap' DEBUG
BASH_HOOK

    chmod 644 "$HOOK_DIR/flow.bash"
    echo "✅ Wrote $HOOK_DIR/flow.bash"
}

write_zsh_hook() {
    mkdir -p "$HOOK_DIR"

    cat > "$HOOK_DIR/flow.zsh" <<'ZSH_HOOK'
# --- Flow Automation Hook: zsh ---
# Captures interactive zsh commands before execution.

__flow_zsh_preexec() {
    local cmd="$1"

    [[ -z "$cmd" ]] && return

    case "$cmd" in
        flow|flow\ *|command\ flow|command\ flow\ *) return ;;
        source\ *~/.flow/hooks/flow.zsh*) return ;;
        source\ *\$HOME/.flow/hooks/flow.zsh*) return ;;
    esac

    command flow _hook "$cmd" >/dev/null 2>&1
}

autoload -Uz add-zsh-hook
add-zsh-hook -d preexec __flow_zsh_preexec 2>/dev/null || true
add-zsh-hook preexec __flow_zsh_preexec
ZSH_HOOK

    chmod 644 "$HOOK_DIR/flow.zsh"
    echo "✅ Wrote $HOOK_DIR/flow.zsh"
}

write_clean_bashrc() {
    backup_file "$HOME/.bashrc"

    cat > "$HOME/.bashrc" <<'EOF'
# ~/.bashrc - Flow-compatible clean Bash config
# Generated by Flow installer.

# Only run in interactive shells.
case $- in
    *i*) ;;
    *) return ;;
esac

# History settings.
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# Useful aliases.
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Load Flow hook.
if [ -f "$HOME/.flow/hooks/flow.bash" ]; then
    source "$HOME/.flow/hooks/flow.bash"
fi
EOF

    echo "✅ Repaired $HOME/.bashrc"
}

write_clean_bash_profile() {
    backup_file "$HOME/.bash_profile"

    cat > "$HOME/.bash_profile" <<'EOF'
# ~/.bash_profile - Flow login-shell loader
# Generated by Flow installer.

# Load normal Bash config first.
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

# Load Flow hook last so it wins even if .bashrc changes later.
if [ -f "$HOME/.flow/hooks/flow.bash" ]; then
    source "$HOME/.flow/hooks/flow.bash"
fi
EOF

    echo "✅ Repaired $HOME/.bash_profile"
}

write_clean_profile() {
    backup_file "$HOME/.profile"

    cat > "$HOME/.profile" <<'EOF'
# ~/.profile - Flow-compatible profile
# Generated by Flow installer.

if [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi
EOF

    echo "✅ Repaired $HOME/.profile"
}

write_zshrc_block() {
    backup_file "$HOME/.zshrc"
    cat > "$HOME/.zshrc" <<'EOF'
# ~/.zshrc - Flow-compatible zsh config
# Generated by Flow installer.

if [ -f "$HOME/.flow/hooks/flow.zsh" ]; then
    source "$HOME/.flow/hooks/flow.zsh"
fi
EOF

    echo "✅ Repaired $HOME/.zshrc"
}

syntax_check() {
    echo "🔍 Checking syntax..."
    bash -n "$HOME/.bashrc"
    bash -n "$HOME/.bash_profile"
    bash -n "$HOME/.profile"
    bash -n "$HOOK_DIR/flow.bash"

    if command -v zsh >/dev/null 2>&1; then
        zsh -n "$HOME/.zshrc" >/dev/null 2>&1 || true
        zsh -n "$HOOK_DIR/flow.zsh" >/dev/null 2>&1 || true
    fi

    echo "✅ Syntax checks passed"
}

main() {
    echo "🧹 Installing Flow with clean shell startup files..."

    install_binary
    write_bash_hook
    write_zsh_hook
    write_clean_bashrc
    write_clean_bash_profile
    write_clean_profile
    write_zshrc_block
    syntax_check

    cat <<'EOF'

✅ Flow installed successfully.

Restart WSL from PowerShell:
"  exit  "
"  wsl   "

Restart your terminal, or run one of these:
"  exec zsh     # reload zsh   "
"  exec bash    # reload bash  "

Verify:
"  trap -p DEBUG   "

Expected:
  trap -- '__flow_bash_debug_trap' DEBUG

Test:
"  flow start   "
"  echo hello   "
"  flow stop    "
"  flow list    "

Backups were saved as:
  ~/.bashrc.flow_backup.TIMESTAMP
  ~/.bash_profile.flow_backup.TIMESTAMP
  ~/.profile.flow_backup.TIMESTAMP
  ~/.zshrc.flow_backup.TIMESTAMP
  
Uninstall later with:
./uninstall.sh
EOF
}

main "$@"
